server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-circular-references: true

  datasource:
    jdbc-url: ${spring.db.url} # jdbc:oracle:thin:@namsuhwang.synology.me:1521:XE
    username: ${spring.db.user}
    password: ${spring.db.pwd}
    driver-class-name: oracle.jdbc.OracleDriver


logging:
  level:
    com.albee.mydataapi.common.client: DEBUG

feign:
  mydatagateway:
    url: http://localhost:8088/test

mydata:
  client:
    id: MYDATA-CLIENTID-0000000001
    secret: MYDATA-CLIENTSECRET-0000000001




